---
title: "Privacy statement"
output:
  html_document:
    code_folding: hide
    toc: false
    toc_float: true
    collapsed: true
    number_sections: false
    toc_depth: 3
# output:
#   distill::distill_article:
#     highlight: haddock
#     highlight_downlit: false
---

```{=html}
<style> 
  distill-site-header {
    background-color: red;
  }
</style>
```

The Neurolinguistics Lab is committed to protecting the privacy and security of personal information. This privacy statement explains how we collect, use, and safeguard the information you provide when registering your interest in participating in our research through our web form.


**Purpose of Data Collection**

We only collect data through the expression of interest registration form. This form allows us to select and contact prospective participants about taking part in our studies. This information is not used for any research purposes or activities and is not tied to any research project ongoing at the lab, affiliated research groups, or third parties.


**What Information We Collect**

The web form collects basic information, including but not limited to:

Name

Contact details (such as email address and phone number)

Age range

Gender

Information pertinent to experiment participation (e.g. languages spoken)

**Data Storage and Security**

We take the security of your personal information seriously. Your data is stored on secure servers with access limited to authorized personnel only. We implement appropriate technical and organizational measures to prevent unauthorized access, alteration, disclosure, or destruction of your information.

The servers are hosted by the Linguistic Research Infrastructure, University of Zurich, using the RedCap secure server management system. RedCap is compliant with all data protection regulations in Switzerland and the EU.

**Data Sharing and Disclosure**

Your personal information will not be shared with third parties, except as required by law. We do not sell, distribute, or lease your personal information to third parties.

**Your Rights and Choices**

You have the right to:

Access the personal information we hold about you.

Request the correction of inaccurate information.

Withdraw your consent for us to contact you at any time.

Request the deletion of your information from our records.

To exercise any of these rights, please contact us using the details provided below.



**Consent**

By submitting your information through our registration form, you consent to the collection and use of your information as described in this privacy statement.



**Changes to Our Privacy Statement**

We may update this privacy statement from time to time. Any changes will be posted on our website along with the updated privacy statement's effective date.



**Contact Us**

If you have any questions or concerns about this privacy statement or our practices concerning your personal information, please contact us at: neuroling-lab@linguistik.uzh.ch.

**Effective Date: 20/03/2024**

<br>