---
title: "Selected publications"
output:
  html_document:
  #  code_folding: hide
    toc: false
    toc_float: true
    collapsed: true
    number_sections: false
    toc_depth: 3
# output: 
#   distill::distill_article:  
#     highlight: haddock
#     highlight_downlit: false
---
## 2023
Araujo, S., Narang, V., Misra, D., Lohagun, N., Khan, O., Singh, A., Mishra, R. K., Hervais-Adelman, A., Huettig, F. (In Press). A literacy-related color-specific deficit in rapid automatized naming: Evidence from neurotypical completely illiterate and literate adults. Journal of Experimental Psychology: General. 

\
Becker, R., & Hervais-Adelman, A. (2023). Individual theta-band cortical entrainment to speech in quiet predicts word-in-noise comprehension. Cerebral Cortex Communications. [https://doi.org/10.1093/texcom/tgad001](https://doi.org/10.1093/texcom/tgad001)

## 2022

Hervais-Adelman A, Kumar U, Mishra RK, Tripathi VN, Guleria A, Singh JP, Huettig F. How does literacy affect speech processing? Not by enhancing cortical responses to speech, but by promoting connectivity of acoustic-phonetic and graphomotor cortices. The Journal of Neuroscience : the Official Journal of the Society For Neuroscience. PMID 36253084 https://doi.org/10.1523/JNEUROSCI.1125-21.2022 0.475

\
Preisig BC, Riecke L, Hervais-Adelman A. Speech sound categorization: The contribution of non-auditory and auditory cortical regions. Neuroimage. 258: 119375. PMID 35700949 https://doi.org/10.1016/j.neuroimage.2022.119375

\
Preisig BC, Hervais-Adelman A. The Predictive Value of Individual Electric Field Modeling for Transcranial Alternating Current Stimulation Induced Brain Modulation. Frontiers in Cellular Neuroscience. 16: 818703. PMID 35273479 https://doi.org/10.3389/fncel.2022.818703

\
Kliesch M, Becker R, Hervais-Adelman A. Global and localized network characteristics of the resting brain predict and adapt to foreign language learning in older adults. Scientific Reports. 12: 3633. PMID 35256672 https://doi.org/10.1038/s41598-022-07629-y

## 2021

Hervais-Adelman, A. (2021). Neuroimaging of simultaneous conference interpreters. In The Routledge Handbook of Conference Interpreting (pp. 471-487): Routledge.

\
Preisig, B. C., Riecke, L., Sjerps, M. J., Kösem, A., Kop, B. R., Bramson, B., . . . Hervais-Adelman, A. (2021). Selective modulation of interhemispheric connectivity by transcranial alternating current stimulation influences binaural integration. Proceedings of the National Academy of Sciences, 118(7), e2015488118. https://doi.org/10.1073/pnas.2015488118

\
Slivac, K., Hervais-Adelman, A., Hagoort, P., & Flecken, M. (2021). Linguistic labels cue biological motion perception and misperception. Scientific Reports, 11(1), 17239. https://doi.org/10.1038/s41598-021-96649-1

\
Townsend, S. W., & Hervais-Adelman, A. (2021). Speech segmentation: New dogs, old tricks? Current Biology, 31(24), R1580-R1582. https://doi.org/10.1016/j.cub.2021.10.042

## 2020

Becker, R., & Hervais-Adelman, A. (2020). Resolving the Connectome, Spectrally-Specific Functional Connectivity Networks and Their Distinct Contributions to Behavior. eneuro, 7(5), ENEURO.0101-0120.2020. https://doi.org/10.1523/eneuro.0101-20.2020

\
Chavant, M., Hervais-Adelman, A., & Macherey, O. (2020). Perceptual Learning of Vocoded Speech With and Without Contralateral Hearing: Implications for Cochlear Implant Rehabilitation. Journal of Speech, Language, and Hearing Research, 1-10. https://doi.org/10.1044/2020_JSLHR-20-00385

\
Hervais-Adelman, A. (2020). Adolfo M. García. The neurocognition of translation and interpreting. Interpreting, 22(1), 156-161. 

\
Houweling, T., Becker, R., & Hervais-Adelman, A. (2020). The noise-resilient brain: Resting-state oscillatory activity predicts words-in-noise recognition. Brain and Language, 202, 104727. https://doi.org/10.1016/j.bandl.2019.104727

\
Keller, L., Hervais-Adelman, A., & Seeber, K. G. (2020). Language conflict resolution and behavioural executive control measures in simultaneous interpreting. In L. Vandevoorde, J. Daems, & B. Defrancq (Eds.), New Empircal Perspectives on Translation and Interpreting: Routledge.

\
Preisig, B. C., Sjerps, M. J., Hervais-Adelman, A., Kosem, A., Hagoort, P., & Riecke, L. (2020). Bilateral Gamma/Delta Transcranial Alternating Current Stimulation Affects Interhemispheric Speech Sound Integration. Journal of Cognitive Neuroscience, 32(7), 1242-1250. https://doi.org/10.1162/jocn_a_01498

\
Seeber, K. G., Keller, L., & Hervais-Adelman, A. (2020). When the ear leads the eye - the use of text during simultaneous interpretation. Language Cognition and Neuroscience, 35(10), 1480-1494. https://doi.org/10.1080/23273798.2020.1799045

## 2019

Burra, N., Hervais-Adelman, A., Celeghin, A., de Gelder, B., & Pegna, A. J. (2019). Affective blindsight relies on low spatial frequencies. Neuropsychologia, 128, 44-49. https://doi.org/10.1016/j.neuropsychologia.2017.10.009

\
Hervais-Adelman, A., & Babcock, L. (2019). The neurobiology of simultaneous interpreting: Where extreme language control and cognitive control intersect. Bilingualism: Language and Cognition, 23(4), 740-751. https://doi.org/10.1017/s1366728919000324

\
Hervais-Adelman, A., Kumar, U., Mishra, R. K., Tripathi, V. N., Guleria, A., Singh, J. P., . . . Huettig, F. (2019). Learning to read recycles visual cortical networks without destruction. Science Advances, 5(9), eaax0262. https://doi.org/10.1126/sciadv.aax0262

\
Rutten, S., Santoro, R., Hervais-Adelman, A., Formisano, E., & Golestani, N. (2019). Cortical encoding of speech enhances task-relevant acoustic information. Nature Human Behaviour, 3(9), 974-987. https://doi.org/10.1038/s41562-019-0648-9

## 2018

Hervais-Adelman, A., Egorova, N., & Golestani, N. (2018). Beyond bilingualism: multilingual experience correlates with caudate volume. Brain Structure & Function. https://doi.org/10.1007/s00429-018-1695-0

\
Hervais-Adelman, A., Moser-Mercer, B., & Golestani, N. (2018). Commentary: Broca Pars Triangularis Constitutes a "Hub" of the Language-Control Network during Simultaneous Language Translation. Frontiers in Human Neuroscience, 12, 22. https://doi.org/10.3389/fnhum.2018.00022

\
Pascucci, D., Hervais-Adelman, A., & Plomp, G. (2018). Gating by induced Alpha-Gamma asynchrony in selective attention. Human Brain Mapping. https://doi.org/10.1002/hbm.24216


## Up to 2017

Hervais-Adelman, A., Moser-Mercer, B., Murray, M. M., & Golestani, N. (2017). Cortical thickness increases after simultaneous interpretation training. Neuropsychologia, 98, 212-219. https://doi.org/10.1016/j.neuropsychologia.2017.01.008

\
Kartushina, N., Hervais-Adelman, A., Frauenfelder, U. H., & Golestani, N. (2016). Mutual influences between native and non-native vowels in production: Evidence from short-term visual articulatory feedback training. Journal of Phonetics, 57, 21-39. https://doi.org/10.1016/j.wocn.2016.05.001

\
Hervais-Adelman, A., Moser-Mercer, B., & Golestani, N. (2015). Brain functional plasticity associated with the emergence of expertise in extreme language control. Neuroimage, 114, 264-274. https://doi.org/10.1016/j.neuroimage.2015.03.072

\
Hervais-Adelman, A., Moser-Mercer, B., Michel, C. M., & Golestani, N. (2015). fMRI of Simultaneous Interpretation Reveals the Neural Basis of Extreme Language Control. Cerebral Cortex, 25(12), 4727-4739. https://doi.org/10.1093/cercor/bhu158

\
Kartushina, N., Hervais-Adelman, A., Frauenfelder, U. H., & Golestani, N. (2015). The effect of phonetic production training with visual feedback on the perception and production of foreign speech sounds. Journal of the Acoustical Society of America, 138(2), 817. https://doi.org/10.1121/1.4926561

\
Plomp, G., Hervais-Adelman, A., Astolfi, L., & Michel, C. M. (2015). Early recurrence and ongoing parietal driving during elementary visual processing. Scientific Reports, 5, 18733. https://doi.org/10.1038/srep18733

\
Van den Stock, J., Tamietto, M., Hervais-Adelman, A., Pegna, A. J., & de Gelder, B. (2015). Body recognition in a patient with bilateral primary visual cortex lesions. Biological Psychiatry, 77(7), e31-33. https://doi.org/10.1016/j.biopsych.2013.06.023

\
Hervais-Adelman, A., Legrand, L. B., Zhan, M., Tamietto, M., de Gelder, B., & Pegna, A. J. (2015). Looming sensitive cortical regions without V1 input: evidence from a patient with bilateral cortical blindness. Frontiers in Integrative Neuroscience, 9, 51. https://doi.org/10.3389/fnint.2015.00051

\
Van den Stock, J., Tamietto, M., Zhan, M., Heinecke, A., Hervais-Adelman, A., Legrand, L. B., . . . de Gelder, B. (2014). Neural correlates of body and face perception following bilateral destruction of the primary visual cortices. Frontiers in Behavioral Neuroscience, 8, 30. https://doi.org/10.3389/fnbeh.2014.00030

\
Becker, R., Pefkou, M., Michel, C. M., & Hervais-Adelman, A. G. (2014). Corrigendum: Left temporal alpha-band activity reflects single word intelligibility. Frontiers in Systems Neuroscience, 8, 47. https://doi.org/10.3389/fnsys.2014.00047

\
Hervais-Adelman, A., Pefkou, M., & Golestani, N. (2014). Bilingual speech-in-noise: neural bases of semantic context use in the native language. Brain and Language, 132, 1-6. https://doi.org/10.1016/j.bandl.2014.01.009

\
Van den Stock, J., Tamietto, M., Zhan, M., Heinecke, A., Hervais-Adelman, A., Legrand, L. B., . . . de Gelder, B. (2014). Neural correlates of body and face perception following bilateral destruction of the primary visual cortices. Frontiers in Behavioral Neuroscience, 8, 30. https://doi.org/10.3389/fnbeh.2014.00030

\
Golestani, N., Hervais-Adelman, A., Obleser, J., & Scott, S. K. (2013). Semantic versus perceptual interactions in neural processing of speech-in-noise. Neuroimage, 79, 52-61. https://doi.org/10.1016/j.neuroimage.2013.04.049

\
Becker, R., Pefkou, M., Michel, C. M., & Hervais-Adelman, A. G. (2013). Left temporal alpha-band activity reflects single word intelligibility. Frontiers in Systems Neuroscience. https://doi.org/10.3389/fnsys.2013.00121


\
Buetti, S., Tamietto, M., Hervais-Adelman, A., Kerzel, D., de Gelder, B., & Pegna, A. J. (2013). Dissociation between Goal-directed and Discrete Response Localization in a Patient with Bilateral Cortical Blindness. Journal of Cognitive Neuroscience, 25(10), 1769-1775. https://doi.org/10.1162/jocn_a_00404

\
Burra, N., Hervais-Adelman, A., Kerzel, D., Tamietto, M., de Gelder, B., & Pegna, A. J. (2013). Amygdala activation for eye contact despite complete cortical blindness. Journal of Neuroscience, 33(25), 10483-10489. https://doi.org/10.1523/JNEUROSCI.3994-12.2013

\
Hervais-Adelman, A. G., Carlyon, R. P., Johnsrude, I. S., & Davis, M. H. (2012). Brain regions recruited for the effortful comprehension of noise-vocoded words. Language and Cognitive Processes, 27(7-8), 1145-1166. https://doi.org/10.1080/01690965.2012.662280

\
Hervais-Adelman, A., Moser-Mercer, B., & Golestani, N. (2011). Executive control of language in the bilingual brain: integrating the evidence from neuroimaging to neuropsychology. Frontiers in Psychology, 2, 234. https://doi.org/10.3389/fpsyg.2011.00234

\
Hervais-Adelman, A. G., Davis, M. H., Johnsrude, I. S., Taylor, K. J., & Carlyon, R. P. (2011). Generalization of perceptual learning of vocoded speech. Journal of Experimental Psychology: Human Perception and Performance, 37(1), 283-295. https://doi.org/10.1037/a0020772

\
Hervais-Adelman, A. G., Moser-Mercer, B., & Golestani, N. (2011). Executive control of language in the bilingual brain: integrating the evidence from neuroimaging to neuropsychology. Frontiers in Psychology, 2, 234. https://doi.org/10.3389/fpsyg.2011.00234

\
Hervais-Adelman, A., Davis, M. H., Johnsrude, I. S., & Carlyon, R. P. (2008). Perceptual learning of noise vocoded words: effects of feedback and lexicality. Journal of Experimental Psychology: Human Perception and Performance, 34(2), 460-474. https://doi.org/10.1037/0096-1523.34.2.460

\
Davis, M. H., Johnsrude, I. S., Hervais-Adelman, A., Taylor, K., & McGettigan, C. (2005). Lexical information drives perceptual learning of distorted speech: evidence from the comprehension of noise-vocoded sentences. Journal of Experimental Psychology: General, 134(2), 222-241. https://doi.org/10.1037/0096-3445.134.2.222

\
Johnsrude, I., Davis, M. H., & Hervais-Adelman, A. (2005). From sound to meaning: Hierarchical processing in speech comprehension. In D. Pressnitzer, A. de Cheveigné, S. McAdams, & L. Collet (Eds.), Auditory Signal Processing: Physiology, Psychoacoustics, and Models.: Springer Verlag.

