---
title: "Vacancies"
output:
  html_document:
    toc: true
    toc_depth: 3
# output:
#   distill::distill_article:
#     highlight: haddock
#     highlight_downlit: false
---

<!-- \_\_\_\_\_\_\_\_\_\_\_ -->

<!-- ### **Post-Doctoral Position**: Neural Dynamics of Sentence Processing -->

<!-- The *neurolinguisitics* team at the *University of Zurich* is recruiting a post-doctoral researcher with expertise in M/EEG and an interest in the neural basis of speech and language to work on a four-year cross-linguistic multidisciplinary project examining multiple aspects of naturalistic speech processing and reading. The project involves close collaboration between neurolinguists ([Alexis Hervais-Adelman](https://neuroling.github.io/)), computational linguists ([Lena Jäger](https://www.cl.uzh.ch/en/digital-linguistics/people/group-leader/jaeger.html)) and linguists ([Marianne Hundt](https://www.linguistik.uzh.ch/en/about/mitglieder/hundt.html), [Fernando Zúñiga](https://www.isw.unibe.ch/ueber_uns/personen/prof_dr_ziga_fernando/index_ger.html)).  -->

<!-- The successful candidate will be responsible for the implementation of a series of investigations that examine the neural signatures of various combinatorial processes and combine computational linguistic approaches to semantic embedding spaces with temporally resolved brain recordings in order to elucidate the neural signatures of combinatorial meaning-building operations using MEG.   -->

<!-- **Person Specification:**  -->

<!-- You have a strong methodological background M/EEG, an interest in neurolinguistics and a passion for multidisciplinary research. You are able to communicate and collaborate productively with scholars of different disciplines. You are solution-oriented, well-organised and enjoy taking the lead. You share your expertise with other members of the team and actively contribute to project development. You have a desire to learn new techniques and determination to master complex analyses.   -->

<!-- **Requirements:**  -->

<!-- -   PhD in a relevant discipline (e.g. Cognitive neuroscience of language or a related field)  -->

<!-- -   Significant expertise in M/EEG, including data acquisition, preprocessing and advanced analysis   -->

<!-- -   Programming skills required for data analysis and experimental design (e.g. Psychtoolbox, PsychoPy, MNE-python, scikit-learn)  -->

<!-- <!-- -->

<!-- -   Excellent written and spoken English  -->

<!-- -   Experience supervising students (MSc./Ph.D.) and research assistants  -->

<!-- -    A proven record of publication of M/EEG experiments in peer-reviewed journals appropriate for the career stage  -->

<!-- Desirable  -->

<!-- -   Flexibility to travel for off-site data acquisition  -->

<!-- <!-- -->

<!-- -   Analysis of time-resolved imaging data using temporal response function   -->

<!-- -   Familiarity with multivariate analysis methods including decoding/encoding approaches  -->

<!-- **The Team**  -->

<!-- The Neurolinguistics group in the Department of Psychology at the University of Zurich investigates the neural basis of language using multimethodological approaches including M/EEG, fMRI and brain stimulation. In addition to affiliation in the Department of Psychology, the successful candidate will benefit from an inspiring multidisciplinary research environment thanks to close contact with the [NCCR Evolving Language](https://evolvinglanguage.ch/), the [Zurich Centre for Linguistics](https://www.linguistik.uzh.ch/de.html) and the [Zurich Centre for Neuroscience](https://www.neuroscience.uzh.ch/en.html).   -->

<!-- We offer an inspiring research environment in an enthusiastic team, and the possibility of developing your profile within the scope of the project at one of Europe's leading (LERU) universities in one of the top ten most livable cities world-wide.  -->

<!-- **Desired start date**: as soon as practicable, flexible for the appropriate candidate.   -->

<!-- For further details or informal inquiries, please contact: Prof. Dr. Alexis Hervais-Adelman, [alexis.hervais-adelman\@psychologie.uzh.ch](mailto:alexis.hervais-adelman@psychologie.uzh.ch)  -->

<!-- Applications, with the reference "DNL02",  including your CV, list of publications (if applicable), motivation letter, names of two referees as a single PDF file should be sent to [Sarah.Krause\@uzh.ch](mailto:Sarah.Krause@uzh.ch). Applications will be considered until the vacancy is filled.  -->



<!-- \_\_\_\_\_\_\_\_\_\_\_ -->

<!-- ### **Master Thesis:** Machine Learning, EEG Neurofeedback and degraded speech perception -->

<!-- Reduced speech comprehension due to hearing impairments which can have dramatic consequences for quality of life. -->

<!-- Our project aims at gaining fundamental knowledge on the neurocognitive basis of our ability to comprehend degraded speech in acoustically challenging situations. We will use *electroencephalography* (EEG) and *machine learning decoding* to investigate patterns of brain activity associated with better speech in noise comprehension. -->

<!-- The ultimate goal of this project is to define better targets for future neurofeedback. -->

<!--  - We offer hands-on experience collecting high-quality electrophysiological data and applying advanced signal processing and analysis techniques.     -->

<!--  - Number of theses on this project: 2-3 -->

<!--  - Starting date negotiable -->

<!-- For more details, contact Dr. Gorka Fraga-Gonzalez, [gorka.fragagonzalez\@uzh.ch](mailto:gorka.fragagonzalez@uzh.ch){.email} -->

  \_\_\_\_\_\_\_\_\_\_\_

## Infant Cry Perception and Processing

Human neonatal infants are reliant on caregivers for their fundamental survival needs; however, infants are also restricted to capturing caregiver attention or signalling their needs via crying. As such, appropriate cry perception and care giving response by the caregiver is essential for healthy infant development. Previous work has demonstrated that neonates are born producing accented cries that match the dominant pitch contour of the native language in which they gestated, this matching pitch contour may produce familiarity effects for caregivers of the same language either enhancing the perceptual salience of the cry or mitigating its aversive nature. We are interested in understanding the objective and subjective perceptual results of infant cry accent/caregiver experience, as well as how neural responses in the infant cry perception network may differ along the same experimental factors.

We have availability for two students to work on this project at University of Zurich:

### **Master Thesis:** Differential neural responses in the cry perception network due to neonatal cry accent and caregiver experience.

This project branch focuses on the cognitive neuroscience branch of the study using functional MRI to investigate how the cry perception network may differentially respond when cries have native/non-native accents, and how this effect is modulated by the caregiving experience of the listener.

We are looking for a driven student interested in cognitive neuroscience in some of the following areas: auditory perception, socioaffective communication, or functional neuroimaging. The chosen student must be comfortable working with MATLAB (or Python) and have fundamental understanding of neuroimaging principles, as well as being comfortable with supervision in English and working directly with research participants. Project duties will involve the collection and analysis of functional MRI data, providing valuable first-hand experience for students viewing a career in neuroimaging. There are also opportunities for developing experience and knowledge of auditory neuroscience, Bayesian and frequentist statistical modelling, and signal processing for neuroscience.

<!-- Number of theses: 1-2 -->

For more details, contact Huw Swanborough -- [huw.swanborough\@uzh.ch](mailto:huw.swanborough@uzh.ch){.email}

### **Master Thesis:** The influence of care-giver experience and neonatal cry accent on objective and subjective perception of infant crying.

In this strand, the student will focus on the perceptual aspect of the project, utilising eye-tracking and subjective participant responses to investigate the perceptual impact of cry accent and caregiving experience.

We are looking for a driven student interested in cognitive neuroscience in some of the following areas: psychophysics/psychoacoustics, complex behavioural modelling, auditory perception, socioaffective communication. The student must be comfortable working with R (preferably also MATLAB or Python) and be prepared to engage with complex statistical models (under supervision), as well as a comfort with supervision in English and working directly with research participants. Project duties will involve the collection and analysis of eye-tracking and behavioural data in laboratory conditions and would suite students viewing careers in cognitive neuroscience or seeking to develop skills in auditory perception, statistics, and/or signal processing. There will be opportunities to engage with the more complex side of signal processing, auditory perception, and statistics if desired.

<!-- Number of theses: 1-2 -->

For more details, contact Huw Swanborough -- [huw.swanborough\@uzh.ch](mailto:huw.swanborough@uzh.ch){.email}

  \_\_\_\_\_\_\_\_\_\_\_

## Speech comprehension

### **Master Thesis:** Audio and video-driven features in audiovisual speech perception

The visual component of speech plays an important part in real-world communication, as evidenced by the literature, and by mask-wearing during the Covid19 pandemic. This audio-visual comprehension gain plays a yet greater role for those living with hearing impairment -- a majority of the ageing population -- so understanding the mechanisms which underpin audio-visual integration is important for the development of advanced hearing aids and for the hearing impaired. Despite a concerted effort to this end over the past decades, several aspects of these processes remain unclear -- not least with respect to the role of temporal and categorical cues carried by the visual component of speech, and to the putative tuning of neural circuitry due to co-evolution of language production and perception. This project aims to disentangle these effects through a set of behavioural experiments on degraded audio-visual speech comprehension carried out online and in the lab. Findings will inform further studies with brain-imaging and contribute to the development of solutions for individuals who suffer from hearing impairment. 

For more details, contact Enrico Varano, [enrico.varano\@psychologie.uzh.ch](mailto:enrico.varano@uzh.ch){.email}

### **Master Thesis:** Investigating motor contributions to speech perception using transcranial electrical stimulation

Humans excel at the difficult task of parsing degraded speech. This skill, which is apparent when communicating in noisy environments, in the presence of unattended speakers, or in those wearing hearing prostheses, is underpinned by a hierarchy of complex, distributed neural processes. Perhaps surprisingly, evidence suggests neural circuitry involved in speech production and planning thereof plays an important part in speech perception as well. Despite a concerted effort to confirm and describe the contribution of processes in the motor cortex to speech perception, more work is required to elucidate the matter. This project aims to observe such motor contributions to speech perception by employing a transcranial electrical stimulation paradigm. Findings will contribute to the development of solutions for individuals who suffer from hearing impairment. 

For more details, contact Enrico Varano, [enrico.varano\@psychologie.uzh.ch](mailto:enrico.varano@uzh.ch){.email}