---
title: "Our Values and Guidelines"
output:
  html_document:
    toc: true
    toc_float: true
    collapsed: true
    number_sections: false
    toc_depth: 3
# output:
#   distill::distill_article:
#     highlight: haddock
#     highlight_downlit: false
---

```{=html}
<style> 
  distill-site-header {
    background-color: red;
  }
</style>
```
<This document is a work in progress, and will continually develop thanks to input from team members>

### Goals
The Dynamics of Brain and Language Lab and Neurolinguistics Group seek to illuminate the implementation of language in the brain. A key puzzle, but not the only puzzle, is the role of the broad motor system as the substrate for linguistic processing. This line of enquiry requires an interdisciplinary approach, using methods drawn from cognitive neuroscience, experimental psychology, linguistics, psychophysics and more.   

We are not individually masters of everything, and we seek out complementarity of knowledge and skills so that collectively we can address bigger questions.  

A core part of our work is education - the lab should be an environment where we can make mistakes, where we can ask for help and where we can learn new things without fear. 

### Values ###
As a team, we set out core values for ourselves. These develop over time and should be reviewed as necessary. A team is not static, and values evolve to reflect this.  

These values are those that seem crucial today. They are highlighted because they are present, not because they are absent and they serve us well in working together and achieving or proximal and longer-term scientific objectives.  

We do our best to achieve our scientific goals while respecting our values. The values we share are those that enable us to create a supportive and caring environment that promotes collective success and personal fulfilment.  

Each of these values serves to strengthen our commitment to scientific rigour, ethics, fairness and mutual understanding.

**Collegiality**  
Science progresses best through collaboration and sharing. In the lab:  

• We share skills and knowledge. We can solicit input and we give feedback and suggestion freely. This must be balanced with our own objectives and tasks.  

• Respectful constructive criticism is welcome. It serves to help us improve our work and to avoid mistakes, but not to judge or target individuals.  

• Everyone, regardless of status, is encouraged to actively participate in discussion and to support their colleagues.

**Curiosity**  
Curiosity is the essential driver of research. We value:  

• Open-mindendness and exploring new and unexpected domains and topics.  

• Participation in scientific events, and discussions that allow us to gain new perspectives.  

• Inspiration from beyond our core research domain, as inspiration is often found at the intersection of different paths. 

**Respect**  
Respect is essential to our working environment and conditions.  

• Respect for the individual.  

• Respect for academic contributions - we recognise and value the work of all. We understand that the primary currency of academia is authorship and that decisions concerning authorship can be causes of significant friction. Academic contributions must be attributed fairly and transparently.  

• Respect for private life - we encourage a healthy work-life balance. Flexibility and accommodation of individual needs are essential to a sustainable and productive work environment.  

• Respect for experimental participants - when research requires participation of volunteers, their well-being, their confidentiality and their rights are our priorities. We follow stringent ethical guidelines to guarantee their dignity. 

**Self Empowerment**  
Taking the initiative is a sign of maturity and confidence in one's abilities. We encourage:

• Pro-activity - in the face of challenges, it is always preferable to inform of problems swiftly, to propose solutions, and whenever possible, to implement solutions.

• Autonomy - building confidence to take operational decisions concerning your work increases your autonomy. Increased autonomy is essential to the management of projects and the ability to contribute effectively to the lab's work. 

• Responsibility - taking the initiative implies responsibility for the consequences of decisions, be they positive or negative. Sharing lessons and solutions with the team contributes to continuing improvements.  

• Knowing when to ask for help - if, after trying to find solutions, non present themselves, it is time to ask for help for the person you imagine to be best placed to assist you. 

**Transparency**  
In research, transparency is intimately related to honesty. It is essential to ensuring public trust and to healthy collaboration. This implies that we:  

• Clearly document research (plans, code, data, analyses) in order to ensure accessibility to all, in compliance with the **FAIR** (Findable, Accessible, Interoperable, Reusable) principles.  

• Recognise that comprehensive documentation serves to ease not only current collaboration but the work of future colleagues.  

• Encourage rapid reporting of problems or errors that may arise, in order to find solutions together and to continue to progress and to learn.  

### The Rules ### 
Some simple rules emerge that will allow us to work according to these values. 
In addition to these rules, there are guidelines elsewhere on how to do certain tasks.  
**Try to have fun, despite the apparent constraints**  

• **ANTICIPATE:** Everyone has a busy schedule. To allow for high-quality feedback to be provided, it is important to allow enough time (at least 7 days) before a deadline. 

• **INFORM:** If you are ill or unavailable on a work day between 10h00 and 16h00, let the team know, so that appropriate accommodations can be made and no unnecessary concern arises.
 
• **PLAN:** To avoid unnecessary or surprise hold-ups to project progress, plan vacations and absences, and unless they are unavoidable, ensure they are approved and recorded in advance. 

• **REPORT:** Keep project-management plans updated. When tasks are completed, celebrate, share, and move on to the next. If progress is slower than anticipated, share the problems, so that they can be solved.

Perfection is the enemy of the good. Aim to achieve the best you can. Next time will be even better. 

